puts "Deleting previous data"
Student.destroy_all
puts "Deleted all students"
User.destroy_all
puts "Deleted all users"

puts "Seeding new data"
puts "Creating new users"
u1	=	User.create(first_name: 'David', last_name: 'Williams', email: 'dwilliams@gmail.com', password: 'password', phone_number: '714-398-2878', address: '796 Main St', city: 'San Fernando', state: 'CA', zip_code: '93142')
u2	=	User.create(first_name: 'Alice', last_name: 'Vargas', email: 'avargas@gmail.com', password: 'password', phone_number: '804-809-7698', address: '704 Pine St', city: 'San Fernando', state: 'CA', zip_code: '92072')
u3	=	User.create(first_name: 'Olivia', last_name: 'Qureshi', email: 'oqureshi@gmail.com', password: 'password', phone_number: '779-892-8447', address: '031 Oak St', city: 'Hawthorne', state: 'CA', zip_code: '92571')
u4	=	User.create(first_name: 'Emily', last_name: 'Vargas', email: 'evargas@gmail.com', password: 'password', phone_number: '233-382-5309', address: '259 Elm St', city: 'Lancaster', state: 'CA', zip_code: '91560')
u5	=	User.create(first_name: 'Olivia', last_name: 'Nguyen', email: 'onguyen@gmail.com', password: 'password', phone_number: '234-396-8692', address: '453 Main St', city: 'Culver City', state: 'CA', zip_code: '91556')
u6	=	User.create(first_name: 'Olivia', last_name: 'Edwards', email: 'oedwards@gmail.com', password: 'password', phone_number: '734-148-6502', address: '662 Oak St', city: 'Compton', state: 'CA', zip_code: '91280')
u7	=	User.create(first_name: 'Frank', last_name: 'Rodriguez', email: 'frodriguez@gmail.com', password: 'password', phone_number: '293-537-4623', address: '697 Elm St', city: 'Brentwood', state: 'CA', zip_code: '93415')
u8	=	User.create(first_name: 'Henry', last_name: 'Jackson', email: 'hjackson@gmail.com', password: 'password', phone_number: '283-737-1506', address: '084 Main St', city: 'Culver City', state: 'CA', zip_code: '92528')
u9	=	User.create(first_name: 'Emily', last_name: 'Connor', email: 'econnor@gmail.com', password: 'password', phone_number: '329-313-5462', address: '656 Oak St', city: 'Santa Monica', state: 'CA', zip_code: '90158')
u10	=	User.create(first_name: 'Quinn', last_name: 'Thompson', email: 'qthompson@gmail.com', password: 'password', phone_number: '954-422-6262', address: '493 Oak St', city: 'Beverly Hills', state: 'CA', zip_code: '90449')
u11	=	User.create(first_name: 'Zoe', last_name: 'Perez', email: 'zperez@gmail.com', password: 'password', phone_number: '102-210-1958', address: '207 Main St', city: 'Burbank', state: 'CA', zip_code: '92107')
u12	=	User.create(first_name: 'Taylor', last_name: 'Rodriguez', email: 'trodriguez@gmail.com', password: 'password', phone_number: '166-773-7215', address: '640 Pine St', city: 'Santa Monica', state: 'CA', zip_code: '93025')
u13	=	User.create(first_name: 'Noah', last_name: 'Xu', email: 'nxu@gmail.com', password: 'password', phone_number: '837-357-5069', address: '652 Elm St', city: 'Compton', state: 'CA', zip_code: '90945')
u14	=	User.create(first_name: 'Will', last_name: 'Rodriguez', email: 'wrodriguez@gmail.com', password: 'password', phone_number: '634-541-1165', address: '200 Elm St', city: 'Hawthorne', state: 'CA', zip_code: '91113')
u15	=	User.create(first_name: 'Emily', last_name: 'Hernandez', email: 'ehernandez@gmail.com', password: 'password', phone_number: '220-866-1759', address: '606 Main St', city: 'Pomona', state: 'CA', zip_code: '91581')
u16	=	User.create(first_name: 'Sophia', last_name: 'Martinez', email: 'smartinez@gmail.com', password: 'password', phone_number: '723-874-3301', address: '772 Elm St', city: 'Long Beach', state: 'CA', zip_code: '91089')
u17	=	User.create(first_name: 'Jack', last_name: 'Vargas', email: 'jvargas@gmail.com', password: 'password', phone_number: '315-488-4219', address: '669 Elm St', city: 'Hawthorne', state: 'CA', zip_code: '91570')
u18	=	User.create(first_name: 'Olivia', last_name: 'Davis', email: 'odavis@gmail.com', password: 'password', phone_number: '363-401-1263', address: '603 Elm St', city: 'Culver City', state: 'CA', zip_code: '90292')
u19	=	User.create(first_name: 'Frank', last_name: 'Jackson', email: 'fjackson@gmail.com', password: 'password', phone_number: '602-583-7124', address: '238 Main St', city: 'Calabasas', state: 'CA', zip_code: '91726')
u20	=	User.create(first_name: 'Yara', last_name: 'Yi', email: 'yyi@gmail.com', password: 'password', phone_number: '457-774-7108', address: '873 Pine St', city: 'Malibu', state: 'CA', zip_code: '92096')
puts "Creating Admin users"
u21	=	User.create(admin: true, first_name: 'Jose', last_name: 'Fletes', email: 'jfletes@lamusart.org', password: 'eagles40', phone_number: '706-791-5824', address: '959 N Placentia Ave.', city: 'Fullerton', state: 'CA', zip_code: '92831')


puts "Creating new students"
s1	=	Student.create(first_name: "Taylor", last_name: "Thompson", birthday: Date.new(2005, 7, 6), gender: "Male", interest: "Dance", user_id: u15.id)
s2	=	Student.create(first_name: "Grace", last_name: "Edwards", birthday: Date.new(2013, 6, 2), gender: "Non-binary/non-conforming", interest: "Music", user_id: u18.id)
s3	=	Student.create(first_name: "Charlie", last_name: "Ingram", birthday: Date.new(2016, 5, 27), gender: "Male", interest: "Drama", user_id: u15.id)
s4	=	Student.create(first_name: "Grace", last_name: "Jackson", birthday: Date.new(2007, 6, 18), gender: "Non-binary/non-conforming", interest: "Drama", user_id: u16.id)
s5	=	Student.create(first_name: "Victoria", last_name: "Jackson", birthday: Date.new(2015, 2, 4), gender: "Male", interest: "Drama", user_id: u12.id)
s6	=	Student.create(first_name: "Frank", last_name: "Thompson", birthday: Date.new(2006, 6, 7), gender: "Prefer not to respond", interest: "Art", user_id: u19.id)
s7	=	Student.create(first_name: "Victoria", last_name: "Yi", birthday: Date.new(2005, 9, 12), gender: "Prefer not to respond", interest: "Music", user_id: u10.id)
s8	=	Student.create(first_name: "Quinn", last_name: "Qureshi", birthday: Date.new(2010, 12, 18), gender: "Female", interest: "Drama", user_id: u6.id)
s9	=	Student.create(first_name: "Parker", last_name: "Davis", birthday: Date.new(2016, 4, 11), gender: "Non-binary/non-conforming", interest: "Drama", user_id: u11.id)
s10	=	Student.create(first_name: "Mia", last_name: "Lee", birthday: Date.new(2016, 11, 5), gender: "Male", interest: "Music", user_id: u6.id)
s11	=	Student.create(first_name: "Henry", last_name: "Chen", birthday: Date.new(2013, 7, 14), gender: "Male", interest: "Dance", user_id: u6.id)
s12	=	Student.create(first_name: "Isabelle", last_name: "Chen", birthday: Date.new(2006, 3, 5), gender: "Non-binary/non-conforming", interest: "Music", user_id: u20.id)
s13	=	Student.create(first_name: "Charlie", last_name: "Lee", birthday: Date.new(2016, 5, 26), gender: "Male", interest: "Dance", user_id: u6.id)
s14	=	Student.create(first_name: "Quinn", last_name: "Martinez", birthday: Date.new(2014, 4, 27), gender: "Prefer not to respond", interest: "Music", user_id: u14.id)
s15	=	Student.create(first_name: "Parker", last_name: "Edwards", birthday: Date.new(2016, 12, 12), gender: "Male", interest: "Drama", user_id: u17.id)
s16	=	Student.create(first_name: "Victoria", last_name: "Qureshi", birthday: Date.new(2018, 2, 27), gender: "Female", interest: "Music", user_id: u17.id)
s17	=	Student.create(first_name: "Sophia", last_name: "Brown", birthday: Date.new(2013, 5, 9), gender: "Prefer not to respond", interest: "Music", user_id: u9.id)
s18	=	Student.create(first_name: "Bob", last_name: "Davis", birthday: Date.new(2016, 6, 26), gender: "Non-binary/non-conforming", interest: "Dance", user_id: u1.id)
s19	=	Student.create(first_name: "Charlie", last_name: "Lee", birthday: Date.new(2016, 8, 8), gender: "Non-binary/non-conforming", interest: "Music", user_id: u1.id)
s20	=	Student.create(first_name: "Frank", last_name: "Smith", birthday: Date.new(2016, 8, 10), gender: "Non-binary/non-conforming", interest: "Art", user_id: u17.id)
s21	=	Student.create(first_name: "Uma", last_name: "Thompson", birthday: Date.new(2006, 3, 26), gender: "Non-binary/non-conforming", interest: "Music", user_id: u11.id)
s22	=	Student.create(first_name: "Emily", last_name: "Jackson", birthday: Date.new(2011, 12, 19), gender: "Male", interest: "Music", user_id: u1.id)
s23	=	Student.create(first_name: "Olivia", last_name: "Brown", birthday: Date.new(2018, 10, 13), gender: "Male", interest: "Drama", user_id: u12.id)
s24	=	Student.create(first_name: "Uma", last_name: "O'Connor", birthday: Date.new(2008, 6, 22), gender: "Female", interest: "Music", user_id: u13.id)
s25	=	Student.create(first_name: "Xavier", last_name: "Zhang", birthday: Date.new(2014, 6, 1), gender: "Prefer not to respond", interest: "Drama", user_id: u15.id)
s26	=	Student.create(first_name: "Victoria", last_name: "Upton", birthday: Date.new(2014, 7, 6), gender: "Male", interest: "Drama", user_id: u1.id)
s27	=	Student.create(first_name: "Henry", last_name: "Fisher", birthday: Date.new(2010, 7, 19), gender: "Non-binary/non-conforming", interest: "Dance", user_id: u17.id)
s28	=	Student.create(first_name: "Henry", last_name: "Xu", birthday: Date.new(2013, 1, 23), gender: "Male", interest: "Drama", user_id: u14.id)
s29	=	Student.create(first_name: "David", last_name: "Jackson", birthday: Date.new(2010, 2, 26), gender: "Non-binary/non-conforming", interest: "Drama", user_id: u2.id)
s30	=	Student.create(first_name: "Riley", last_name: "Yi", birthday: Date.new(2005, 8, 21), gender: "Prefer not to respond", interest: "Art", user_id: u16.id)
s31	=	Student.create(first_name: "Bob", last_name: "Garcia", birthday: Date.new(2016, 8, 5), gender: "Female", interest: "Art", user_id: u19.id)
s32	=	Student.create(first_name: "Zoe", last_name: "Rodriguez", birthday: Date.new(2008, 11, 23), gender: "Prefer not to respond", interest: "Music", user_id: u6.id)
s33	=	Student.create(first_name: "Liam", last_name: "Perez", birthday: Date.new(2006, 6, 22), gender: "Female", interest: "Art", user_id: u8.id)
s34	=	Student.create(first_name: "Olivia", last_name: "Fisher", birthday: Date.new(2015, 7, 7), gender: "Female", interest: "Dance", user_id: u20.id)
s35	=	Student.create(first_name: "Parker", last_name: "Brown", birthday: Date.new(2015, 10, 1), gender: "Female", interest: "Drama", user_id: u18.id)
s36	=	Student.create(first_name: "Jack", last_name: "Upton", birthday: Date.new(2005, 10, 9), gender: "Female", interest: "Dance", user_id: u8.id)
s37	=	Student.create(first_name: "Uma", last_name: "Rodriguez", birthday: Date.new(2013, 6, 9), gender: "Female", interest: "Art", user_id: u20.id)
s38	=	Student.create(first_name: "Uma", last_name: "Jackson", birthday: Date.new(2007, 6, 20), gender: "Prefer not to respond", interest: "Music", user_id: u7.id)
s39	=	Student.create(first_name: "Liam", last_name: "Xu", birthday: Date.new(2017, 7, 23), gender: "Prefer not to respond", interest: "Music", user_id: u10.id)
s40	=	Student.create(first_name: "Sophia", last_name: "Williams", birthday: Date.new(2016, 1, 15), gender: "Non-binary/non-conforming", interest: "Drama", user_id: u20.id)
s41	=	Student.create(first_name: "Sophia", last_name: "Rodriguez", birthday: Date.new(2011, 3, 8), gender: "Male", interest: "Music", user_id: u13.id)
s42	=	Student.create(first_name: "Grace", last_name: "Hernandez", birthday: Date.new(2017, 3, 18), gender: "Prefer not to respond", interest: "Music", user_id: u14.id)
s43	=	Student.create(first_name: "Riley", last_name: "Upton", birthday: Date.new(2014, 1, 21), gender: "Male", interest: "Dance", user_id: u6.id)
s44	=	Student.create(first_name: "Mia", last_name: "Rodriguez", birthday: Date.new(2017, 1, 22), gender: "Male", interest: "Drama", user_id: u14.id)
s45	=	Student.create(first_name: "Taylor", last_name: "Thompson", birthday: Date.new(2009, 8, 8), gender: "Prefer not to respond", interest: "Drama", user_id: u5.id)
s46	=	Student.create(first_name: "Zoe", last_name: "Yi", birthday: Date.new(2015, 1, 1), gender: "Non-binary/non-conforming", interest: "Dance", user_id: u2.id)
s47	=	Student.create(first_name: "Henry", last_name: "Yi", birthday: Date.new(2014, 4, 27), gender: "Prefer not to respond", interest: "Art", user_id: u16.id)
s48	=	Student.create(first_name: "Noah", last_name: "Edwards", birthday: Date.new(2012, 12, 20), gender: "Prefer not to respond", interest: "Music", user_id: u11.id)
s49	=	Student.create(first_name: "Quinn", last_name: "Martinez", birthday: Date.new(2008, 7, 21), gender: "Non-binary/non-conforming", interest: "Art", user_id: u18.id)

puts "Done seeding!"